name: Hmm Copy A File

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Copy 📁
        run: |
          mkdir -p ./docs/
          cp ./redirect.html ./docs/index.html
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: github-pages
          folder: docs